### ISSUE TITLE
Angular dashboard is deprecated

### ISSUE THREAD

**Issue by crstian19** [kyouheicf/cloudflare-graphql-grafana#1]
![image](https://github.com/kyouheicf/cloudflare-graphql-grafana/assets/21632768/13676d7f-7ecc-4637-b4bf-a06d5d100327)

**Comment by kyouheicf** [comment]
@crstian19 thank you for letting me know the notice.
This is because I use this plugin, which will be affected by this deprecation.
I can do nothing at the moment for this community-based datasource plugin.
- [fifemon/graphql-datasource: Grafana datasource plugin to query data from a GraphQL API](https://github.com/fifemon/graphql-datasource)

and the discussion has been already happening at the following issue
- [Plugin at risk of deprecation · Issue #89 · fifemon/graphql-datasource](https://github.com/fifemon/graphql-datasource/issues/89)
